### ISSUE TITLE
Expose "version" field of existing applications

### ISSUE THREAD

**Issue by seh** [willroden/marathon-client#14]
When querying for or receiving a recently created record of a running application, Marathon provides [a "version" field](https://github.com/mesosphere/marathon/blob/45f2e479a5ce9b1586a6f140d2b4df05619ab8d6/src/main/scala/mesosphere/marathon/api/v2/json/V2AppDefinition.scala#L70), which is the time at which the application was created or last updated. The time(stamp) arrives to us as a string, but [the documentation mentions that it's produced using Joda-Time's `ISODateTimeFormat` class](https://github.com/mesosphere/marathon/blob/c7624e0c3778da02919e743e8b9eda7248acd1a1/src/main/scala/mesosphere/marathon/state/Timestamp.scala#L45).

Expose this field on the `mesosphere.marathon.client.model.v2.App` class, either as a `String` as received from Marathon, or perhaps translated to either a `org.joda.time.DateTime` or a `long` obtained via `DateTime#getMillis()`.

The former `String` treatment is easiest and most consistent with the rest of the library, but it then forces each consumer to figure out how to parse that date-time string. Against though, doing more would introduce a dependency of the Joda-Time library.

**Comment by mjakubowski84** [comment]
It would be better to not introduce dependency do Joda. Let's stay with String atm,

**Comment by seh** [comment]
I had written that comment before I was using Java 8 daily. Now there's `java.time.Instant`, but [`Instant#parse(CharSequence)`](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#parse-java.lang.CharSequence) is available for clients of this library to use easily enough.
