### ISSUE TITLE
Publish another release

### ISSUE THREAD

**Issue by seh** [willroden/marathon-client#20]
With the recent closure of the following PRs, I'd appreciate a fresh release to take advantage of these changes in my project.
- #13
- #15
- #19

The only other immediate change I had considered advocating was upgrading Feign to something newer, though my project is pinned for now at using Ribbon version 2.0.0.

**Comment by gerlowskija** [comment]
+1, I'd really like to make use of #15, but can't feasibly do so without a release.

**Comment by mjakubowski84** [comment]
Here you go.

**Comment by gerlowskija** [comment]
Thank you!  Much appreciated!

I don't see the release available in Maven Central.  Has it been published (and this is just lag), or is that still forthcoming?

**Comment by seh** [comment]
Thank you!

**Comment by seh** [comment]
It looks like we still need to run [`mvn deploy`](http://central.sonatype.org/pages/apache-maven.html#nexus-staging-maven-plugin-for-deployment-and-release).

**Comment by mjakubowski84** [comment]
@seh If you mean publishing it to Maven Central, then, unfortunately, I do not have rights to cc.roden group. I guess we have to ask @WillAbides for that. Or maybe there is another way I do not know about?

**Comment by seh** [comment]
I had suspected this would be a problem. Without further reading, I don't know how one manages those publishing rights. Presumably @WillAbides would have to grant permission to others, or share the JIRA credentials alluded to [here](http://central.sonatype.org/pages/apache-maven.html#distribution-management-and-authentication).
