### ISSUE TITLE
Make HTTP response status code available publicly from MarathonException

### ISSUE THREAD

**Issue by seh** [willroden/marathon-client#5]
At present, class `mesosphere.marathon.client.utils.MarathonException` includes a _private_ field named "status", which captures the HTTP response status code that motivated it being thrown. Expose this field publicly either by making the field public (and, preferably, final) or via a public accessor method such as

```
public int status() {
  return status;
}
```

Why? For methods like `Marathon#deleteApp()`, there's no way to tell whether a failure arose because the application in question didn't exist, or because it did exist but couldn't be deleted. Marathon responds with 404 in the former case. Callers are stuck parsing the message provided by `MarathonException#getMessage()` in order to discern the difference.

The same argument applies to `Marathon#createApp()`. If an application with the given ID already exists, Marathon responds with 409. I'd like to be able to detect that case.

**Comment by WillAbides** [comment]
This is resolved in release 0.4.9

**Comment by seh** [comment]
We can close this one now. #11 is sufficient.
